# Generated by Django 4.1.3 on 2022-12-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCCD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cccd', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('stt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GetInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=12)),
                ('location', models.CharField(max_length=300)),
                ('guardian', models.CharField(max_length=200)),
                ('queuenumber', models.CharField(max_length=6)),
                ('cccd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cccd')),
            ],
        ),
    ]
