# Generated by Django 4.1.3 on 2022-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='day',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='month',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='stt',
            field=models.IntegerField(unique=True),
        ),
    ]
